### ISSUE TITLE
Please let us know if we support queue group functionality in nats-mq bridge like our Go bridge version

### ISSUE THREAD

**Issue by gstaware** [nats-io/nats-jms-mq-bridge#189]
Please let us know if we support queue group functionality in nats-mq bridge like our Go bridge version. If yes, please share the details. If no, kindly let us know if we have plans to develop the same

**Comment by RichardHightower** [comment]
```kotlin 
/**
 * A Message bus represents a message bus system, i.e., IBM MQ, Nats, ActiveMQ, JMS, Rabbit MQ, Kafka, SQS, etc.
 * A message bus has a subject which can be Nats subject or a JMS destination.
 */
data class MessageBusInfo(val name: String, val busType: BusType, val subject: String, val responseSubject: String?=null,
                          val subscriptionGroup:String?="",
                          val clusterName: String)
```

Note `subscriptionGroup` which is the NATS group name. 

This equates to this YAML

```yaml 
...
bridges:
  - name: "natsToIBMMq"
    bridgeType: "REQUEST_REPLY"
    transforms: ["addHeader"]
    source:
      name: "nats"
      busType: "NATS"
      subject: "b-subject"
      subscriptionGroup: "mygroup"
      clusterName: "natsCluster"
...
```
