### ISSUE TITLE
Show how to set up any nats client config in the bridge?

### ISSUE THREAD

**Issue by RichardHightower** [nats-io/nats-jms-mq-bridge#98]
Q: I am setting up config for one of his questions If we have to configure nats-server in the bridge config file with options like connection timeout, max reconnects, reconnectionWait, TLS settings, etc. how can we do that? 

```
natsCluster:
  name: "natsCluster"
  properties: !<nats>
    host: "nats-server"
    port: 4222
    servers: []
    config:
      io.nats.client.reconnect.wait: 3000
      io.nats.client.reconnect.max: 10
      io.nats.client.timeout: 4000
      io.nats.client.opentls: true 
```

See https://javadoc.io/doc/io.nats/jnats/latest/io/nats/client/Options.html for all of the property keys.
